### ISSUE TITLE
Can we add logic to hide/show the underline of headings using # and ## ?

### ISSUE THREAD

**Issue by ngminhkhoa** [jeziellago/compose-markdown#109]
I think we can use something like border-bottom: 0.
Is it possible? Currently, they look quite ugly in some cases.
```
val markdownContent = """
          # Title 
          ## Title
          ### Title
          <h2 style="text-decoration: none, color: red">Title</h2>
	      * [Link](https://example.com)  
	      ![Image](https://example.com/img.png)  
	      <a href="https://www.google.com/">Google</a> 
"""
```

![image](https://github.com/user-attachments/assets/1f7b7a8c-f009-4c42-a47a-91c6ab8766fa)

Thanks!

**Comment by jeziellago** [comment]
Hi @ngminhkhoa 
I'm going to release a new version where by default there is no heading break line, but the lib give you an option to set a color to show it.
