### ISSUE TITLE
Add a way to enable/disable ripple on markdown text composable.

### ISSUE THREAD

**Issue by robercoding** [jeziellago/compose-markdown#111]
Currently clicking on the MarkdownText shows up the ripple. I'd like to have the ability to enable it or not.
<img width="462" alt="image" src="https://github.com/user-attachments/assets/3b4583d0-6923-4d95-890c-3cc8c09ea6c6">

Although the `MarkdownText` gives the ability to add an action happening on click. The ripple still happens it's null.
The `AndroidView` has a `clickable` modifier that is enabled by default, and there's no way to disable it.
`modifier = Modifier.clickable { onClick?.let { it() } }.then(modifier)`

If this clickable is the responsible for adding the ripple then I see 3 ways to add the option to enable it or not:
- I believe adding a parameter to the MarkdownText composable that enables it or not would solve the problem. 
- We could also use the nullability of the `onClick: (() -> Unit)? = null` parameter to do the check. Something like this.
`Modifier.clickable(enabled = onClick != null) { onClick?.let { it() } }` 
Although it looks too aggressive from my point of view. 
- Remove the clickable and let the developer add their own modifier clickable to the AndroidView if they want.

Lib version: 0.5.1

What do you think?

**Comment by SergeyGaponov** [comment]
As a temporary option, defining a custom modifier with the same property is suitable for me:

```
	MarkdownText(
		markdown = "",
		modifier = Modifier
			.clickable(
				enabled = false,
				onClick = {},
			),
	)
```
