### ISSUE TITLE
Having troubles using the dependecy

### ISSUE THREAD

**Issue by nurlan-aliyev** [jeziellago/compose-markdown#12]
I get this error (_maybe the "TAG" version is not on point?_):
**Failed to resolve: com.github.jeziellago:compose-markdown:TAG**

**Comment by Nehoko** [comment]
same problem.

1. cloned fresh kotlin desktop-compose repository
2. added maven repository: 
```kts
repositories {
    mavenCentral()
    maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    google()
    maven ("https://jitpack.io")
}
```
3. added dependency
```kts
dependencies {
    // Note, if you develop a library, you should use compose.desktop.common.
    // compose.desktop.currentOs should be used in launcher-sourceSet
    // (in a separate module for demo project and in testMain).
    // With compose.desktop.common you will also lose @Preview functionality
    implementation(compose.desktop.currentOs)
    implementation("com.github.jeziellago", "compose-markdown", "0.2.6")
}
```
4. got the error:
```bash
Could not resolve com.github.jeziellago:compose-markdown:0.2.6.
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

```

**Comment by jeziellago** [comment]
> same problem.
> 
> 1. cloned fresh kotlin desktop-compose repository
> 2. added maven repository:
> 
> ```kotlin
> repositories {
>     mavenCentral()
>     maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
>     google()
>     maven ("https://jitpack.io")
> }
> ```
> 
> 1. added dependency
> 
> ```kotlin
> dependencies {
>     // Note, if you develop a library, you should use compose.desktop.common.
>     // compose.desktop.currentOs should be used in launcher-sourceSet
>     // (in a separate module for demo project and in testMain).
>     // With compose.desktop.common you will also lose @Preview functionality
>     implementation(compose.desktop.currentOs)
>     implementation("com.github.jeziellago", "compose-markdown", "0.2.6")
> }
> ```
> 
> 1. got the error:
> 
> ```shell
> Could not resolve com.github.jeziellago:compose-markdown:0.2.6.
> Required by:
>     project :
> 
> Possible solution:
>  - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
> ```

Hi @Nehoko,
At the moment, `compose-markdown` works only with android Jetpack Compose.

**Comment by nurlan-aliyev** [comment]
Getting the same type of error, says cannot resolve "project-link:0.2.6"

**Comment by jeziellago** [comment]
> Getting the same type of error, says cannot resolve "project-link:0.2.6"
> 
> Maybe I'm not doing it correctly?

If you're trying it on kotlin desktop-compose, it'll doesn't work.

**Comment by nurlan-aliyev** [comment]
I want to develop an Android app, not a desktop one

**Comment by jeziellago** [comment]
> I want to develop an Android app, not a desktop one
@nurlan-aliyev, try to follow these steps:
1. Open the file `settings.gradle` (it looks like that)
```groovy
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // add jitpack here 👇🏽
        maven { url 'https://jitpack.io' }
       ...
    }
} 
...
```
2. Sync the project
3. Add `compose-markdown` dependency
```groovy
dependencies {
        implementation 'com.github.jeziellago:compose-markdown:0.2.6'
}
```

**Comment by nurlan-aliyev** [comment]
It works now, thanks a lot, I was adding maven to project:build.gradle that was the error

**Comment by Nehoko** [comment]
> > same problem.
> > 
> > 1. cloned fresh kotlin desktop-compose repository
> > 2. added maven repository:
> > 
> > ```kotlin
> > repositories {
> >     mavenCentral()
> >     maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
> >     google()
> >     maven ("https://jitpack.io")
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. added dependency
> > 
> > ```kotlin
> > dependencies {
> >     // Note, if you develop a library, you should use compose.desktop.common.
> >     // compose.desktop.currentOs should be used in launcher-sourceSet
> >     // (in a separate module for demo project and in testMain).
> >     // With compose.desktop.common you will also lose @Preview functionality
> >     implementation(compose.desktop.currentOs)
> >     implementation("com.github.jeziellago", "compose-markdown", "0.2.6")
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. got the error:
> > 
> > ```shell
> > Could not resolve com.github.jeziellago:compose-markdown:0.2.6.
> > Required by:
> >     project :
> > 
> > Possible solution:
> >  - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
> > ```
> 
> Hi @Nehoko,
> At the moment, `compose-markdown` works only with android Jetpack Compose.

Is it really the case?
Error message telling me that gradle cannot find package but nothing about supporting platform

**Comment by jeziellago** [comment]
> > > same problem.
> > > 
> > > 1. cloned fresh kotlin desktop-compose repository
> > > 2. added maven repository:
> > > 
> > > ```kotlin
> > > repositories {
> > >     mavenCentral()
> > >     maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
> > >     google()
> > >     maven ("https://jitpack.io")
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 1. added dependency
> > > 
> > > ```kotlin
> > > dependencies {
> > >     // Note, if you develop a library, you should use compose.desktop.common.
> > >     // compose.desktop.currentOs should be used in launcher-sourceSet
> > >     // (in a separate module for demo project and in testMain).
> > >     // With compose.desktop.common you will also lose @Preview functionality
> > >     implementation(compose.desktop.currentOs)
> > >     implementation("com.github.jeziellago", "compose-markdown", "0.2.6")
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 1. got the error:
> > > 
> > > ```shell
> > > Could not resolve com.github.jeziellago:compose-markdown:0.2.6.
> > > Required by:
> > >     project :
> > > 
> > > Possible solution:
> > >  - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
> > > ```
> > 
> > 
> > Hi @Nehoko,
> > At the moment, `compose-markdown` works only with android Jetpack Compose.
> 
> Is it really the case?
> Error message telling me that gradle cannot find package but nothing about supporting platform

Did you follow these steps https://github.com/jeziellago/compose-markdown/issues/12#issuecomment-924436370
and got the same problem?

**Comment by jeziellago** [comment]
Closing this issue. Let me know if you're having problems yet.
