### ISSUE TITLE
How to set local image by URI?

### ISSUE THREAD

**Issue by 809825706** [jeziellago/compose-markdown#14]

**Comment by YvesKalume** [comment]
I think you can put your image in assets folder, then replace the image url with : file:///android_asset/yourimage.jpg

**Comment by jeziellago** [comment]
> I think you can put your image in assets folder, then replace the image url with : file:///android_asset/yourimage.jpg

Yes, images in `assets` folder works.
like `file:///android_asset/my_image.png`.
