### ISSUE TITLE
Disable click on internal textview

### ISSUE THREAD

**Issue by ale-groundcloud** [jeziellago/compose-markdown#19]
Is it possible to disable the click event on the Internal textview?, I'm using this view on a list and the users can't click on the area where the markdown text is added. If possible the consumer should be able to control events with the clickable modifier or having a click block that receives the text on the clicked area.

**Comment by jeziellago** [comment]
Hello @ale-groundcloud,
>  I'm using this view on a list and the users can't click on the area where the markdown text is added.

Are you using links and the click doesn't work?

**Comment by ale-groundcloud** [comment]
It's the opposite, there are no links and the textview consumes them, not allowing the event to go to the view behind it

**Comment by jeziellago** [comment]
Got it!
I guess these changes will solve it.
https://github.com/jeziellago/compose-markdown/commit/8cfa5a531038f2f65237e32add93aadb19d21dc6

**Comment by jeziellago** [comment]
Try it with [`0.2.8` ](https://github.com/jeziellago/compose-markdown/releases/tag/0.2.8)

**Comment by ale-groundcloud** [comment]
you can check by adding the view to a clickable parent. When you click on the textview area, the event will be consumed and not sent to the parent.

**Comment by jeziellago** [comment]
@ale-groundcloud 
Try the version `0.2.9`. I found the problem and did solve it.
I hope it helps you.
