### ISSUE TITLE
Is possible to Drag & Drop?

### ISSUE THREAD

**Issue by brainer3220** [jeziellago/compose-markdown#20]
I want the Drag & Drop feature for the Markdown view.

But, can't long click feature in view in default.

**Comment by jeziellago** [comment]
Hello @brainer3220 

Try to use [`Modifier.combinedClickable` ](https://developer.android.com/reference/kotlin/androidx/compose/foundation/package-summary#(androidx.compose.ui.Modifier).combinedClickable(kotlin.Boolean,kotlin.String,androidx.compose.ui.semantics.Role,kotlin.String,kotlin.Function0,kotlin.Function0,kotlin.Function0))
