### ISSUE TITLE
[Good to have] Make fonts dependens on compose font settings passed to MaterialTheme

### ISSUE THREAD

**Issue by MairwunNx** [jeziellago/compose-markdown#3]
Why? So it will have a better look with other elements in application, for this we must have MaterialTheme instance or Typography class instance for receiving font parameters.

**Comment by jeziellago** [comment]
Hi @MairwunNx,
Check the [v0.2.0](https://github.com/jeziellago/compose-markdown/releases/tag/0.2.0) about the new supported parameters.
