### ISSUE TITLE
"Cannot access class 'coil.ImageLoader'. Check your module classpath for missing or conflicting dependencies" error when trying to use the composable function

### ISSUE THREAD

**Issue by LennyLizowzskiy** [jeziellago/compose-markdown#31]
![image](https://user-images.githubusercontent.com/46971551/219898822-7240974e-92aa-423b-b8bd-f49c049e6fdb.png)

**Comment by wtesler** [comment]
Same issue

**Comment by charliepank** [comment]
I had the same issue. I added 

```implementation("io.coil-kt:coil:2.3.0") 

to build.gradle to solve it.

**Comment by LennyLizowzskiy** [comment]
> I had the same issue. I added
> 
> ```
> implementation("io.coil-kt:coil:2.3.0") 
> ```
> 
> to build.gradle to solve it.

I understand that library requires coil, but there's nothing about that in README.md

**Comment by jk2pr** [comment]
Just add this in app.gradle file ``implementation 'io.coil-kt:coil:2.3.0'`` issue fixed 👌
