### ISSUE TITLE
Change link color?

### ISSUE THREAD

**Issue by bmaum321** [jeziellago/compose-markdown#34]
Is there any way to change just the link color?

**Comment by MrJero** [comment]
same query

**Comment by ninovanhooff** [comment]
Same

**Comment by ninovanhooff** [comment]
@jeziellago Would you please create a new release, since the main branch contains this property?

**Comment by ninovanhooff** [comment]
For anyone else watching this: if you need this right now, you can use the current buld from the main branch:

`implementation 'com.github.jeziellago:compose-markdown:c26865cd40'`

**Comment by jeziellago** [comment]
New release available [0.3.5](https://github.com/jeziellago/compose-markdown/releases/tag/0.3.5)
