### ISSUE TITLE
Library artifacts can't be used: no artifacts uploaded

### ISSUE THREAD

**Issue by MairwunNx** [jeziellago/compose-markdown#4]
Hi again, I tried to receive your library through jipack and I've a fail, I just can't use it because you don't published artifacts.

As you can see we receiving only sources as artifacts (build logs on jitpack)
![image](https://user-images.githubusercontent.com/39625750/113244095-fe20c700-92bc-11eb-889f-93d037f8e949.png)

Affected published versions: 0.1.0, 0.2.0, snapshot from last commit, snapshot from master branch.

**Comment by jeziellago** [comment]
Hi @MairwunNx,

Check your `settings.gradle` and include `maven { url "https://jitpack.io" }`:
```gradle
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }  // add jitpack
    }
}
```
For me, it works normally.
