### ISSUE TITLE
Feature request: support overflow like Text() does

### ISSUE THREAD

**Issue by charliepank** [jeziellago/compose-markdown#40]
<img width="706" alt="Screenshot 2023-04-05 at 21 26 05" src="https://user-images.githubusercontent.com/6232906/230040109-da5003d2-3325-40cb-a221-9825aed41b54.png">

the Text() example understand the overflow option, but the Markdown() one doesn't

**Comment by charliepank** [comment]
Hey - thanks for picking this up. Do you need any further explanation?

**Comment by jeziellago** [comment]
Feel free to explain how this would be, to better help you

**Comment by charliepank** [comment]
If you look at my example, the 
`
overflow = TextOverflow.Ellipsis
`
means that when the maxlines param is exceeded, it cuts off the excess and adds 3 dots to show there is more. If the user taps on the 3 dots, then the text is expanded so it can all be read, another tap collapses it back to the maxlines length again.

**Comment by Jasperav** [comment]
@jeziellago Is this on the roadmap? It would be useful to have. Tapping it to be expanded is not necessary
