### ISSUE TITLE
Font size is set with DP instead of SP

### ISSUE THREAD

**Issue by isles1217** [jeziellago/compose-markdown#41]
I just noticed this when looking at the source code for the `createTextView` method
```
setTextSize(TypedValue.COMPLEX_UNIT_DIP, mergedStyle.fontSize.value)
```

This should be changed to the following, to ensure text size scaling settings on the device are honored. 
```
setTextSize(TypedValue.COMPLEX_UNIT_SP, mergedStyle.fontSize.value)
```

**Comment by brahmkshatriya** [comment]
why not create a Pull request?
