### ISSUE TITLE
No support for "\n" mark

### ISSUE THREAD

**Issue by tryboxx** [jeziellago/compose-markdown#43]
The `\n` mark in string is ignored when using `MarkdownText` - it appears as an empty space between the words.

![Screenshot_20230512_094800](https://github.com/jeziellago/compose-markdown/assets/16317593/12860525-4248-49e0-b9f5-987e0601835c)

**Comment by jeziellago** [comment]
Hello, @tryboxx 
Can you provide a code snippet to reproduce this error? 
Make sure the content keeps the markdown standards.

**Comment by vitorhugods** [comment]
```markdown
Multiple
Lines
```

Is rendered like:

> MultipleLines


I've seen this behaviour happening on some Markdown editors already, and I remember it annoyed me. But at least GitHub and Confluence/Jira provide a WYSIWYG experience for this.

**Comment by tryboxx** [comment]
Sure @jeziellago, thats my implementation of the string from the screenshot:

`"• low porosity hair\n• medium porosity hair\n• high porosity hair"`

```
MarkdownText(
    markdown = highlightedSection.content,
    color = Color.Black,
    style = AppTheme.typography.normalText2
)
```

**Comment by vitorhugods** [comment]
Keep in mind that [Markdown ignores single line break on purpose](https://daringfireball.net/projects/markdown/syntax#p).

I'm not sure what would be the best solution for this case.

Maybe replacing `\n` with `\n\n` if you are sure that the content wasn't originally written with Markdown in mind.

**Comment by tryboxx** [comment]
You're right, but that's why I reported this issue - in my opinion, every markdown library should handle this case with some workaround, like Swift libraries do. It can be handled on library side, by default.

**Comment by ArjixWasTaken** [comment]
Usually when I want to go insert a new line, but markdown refuses to comply, I just use `<br />`.
It doesn't leave the huge gap that double new lines leave.

(dunno if this library supports the `<br />` tag, I just posted my general solution to this problem)

**Comment by turik2304** [comment]
@jeziellago 
maybe add this plugin?

`.usePlugin(SoftBreakAddsNewLinePlugin.create())`
