### ISSUE TITLE
MarkdownText crashes using coil in Kotlin

### ISSUE THREAD

**Issue by LeomarisReyes** [jeziellago/compose-markdown#58]
https://github.com/jeziellago/compose-markdown

**When I do scroll a lot of time in a LazyColumn using the MarkdownText in compose, a exception is launched:**

StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4188)] [android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4752)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4719)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4693)] [androidx.work.impl.utils.NetworkApi24.registerDefaultNetworkCallbackCompat(NetworkApi24.kt:28)] [androidx.work.impl.constraints.trackers.NetworkStateTracker24.startTracking(NetworkStateTracker.kt:139)] [androidx.work.impl.constraints.trackers.ConstraintTracker.addListener(ConstraintTracker.kt:57)] [androidx.work.impl.constraints.controllers.ConstraintController.replace(ConstraintController.kt:82)] [androidx.work.impl.constraints.WorkConstraintsTrackerImpl.replace(WorkConstraintsTracker.kt:92)] [androidx.work.impl.background.greedy.GreedyScheduler.schedule(GreedyScheduler.java:170)] [androidx.work.impl.background.greedy.DelayedWorkTracker$1.run(DelayedWorkTracker.java:75)]

coil.network.RealNetworkObserver.<init>(NetworkObserver.kt:88)] [coil.network.NetworkObserverKt.NetworkObserver(NetworkObserver.kt:33)] [coil.util.SystemCallbacks.<init>(SystemCallbacks.kt:31)] [coil.RealImageLoader.<init>(RealImageLoader.kt:79)] [coil.ImageLoader$Builder.build(ImageLoader.kt:529)]

Related issue: https://github.com/coil-kt/coil/issues/28

**Comment by jeziellago** [comment]
Did you try to create (outside MarkdownText) and set your own `ImageLoader`?
https://github.com/jeziellago/compose-markdown/blob/b7736f36f1e1fa07701320d0177b5413ddc89584/markdowntext/src/main/java/dev/jeziellago/compose/markdowntext/MarkdownText.kt#L70

**Comment by jeziellago** [comment]
I'm closing this issue due to no answer. Feel free to open again in case of facing another bug.
