### ISSUE TITLE
Missed feature Ellipsis for the markdown text

### ISSUE THREAD

**Issue by TinaT2** [jeziellago/compose-markdown#74]
On `Text` compose we have a feature `overflow = TextOverflow.Ellipsis`.
This is missing on the Markdown text, can you add it to this great library?
Thanks for all.

**Comment by jeziellago** [comment]
Hi, @TinaT2 
The overflow is supported by `truncateOnTextOverflow` option that has the same behavior that `TextOverflow.Ellipsis`.

**Comment by TinaT2** [comment]
> Hi, @TinaT2 The overflow is supported by `truncateOnTextOverflow` option that has the same behavior that `TextOverflow.Ellipsis`.

Is there in the `MarkdownText` composable fields?
I can't find it on the 0.3.6 version.
