### ISSUE TITLE
library not pulling

### ISSUE THREAD

**Issue by burhankhanzada** [jeziellago/compose-markdown#8]
i have done all steps mentioned in readme correctly but library doesn't fetched `MarkdownText` not found

**Comment by jeziellago** [comment]
Hi @burhankhanzada 
Try it https://jitpack.io/#jeziellago/compose-markdown/0.2.3

**Comment by franticnick** [comment]
I'm not sure if it's related but when I want to start the project I'm getting: "403 forbidden" for the dependency:

https://jcenter.bintray.com/com/github/jeziellago/compose-markdown/0.2.3/compose-markdown-0.2.3.pom

Screenshot from the browser:

![image](https://user-images.githubusercontent.com/674741/126237670-5c84b53e-595f-4a83-bf54-1227c42cd938.png)

**Comment by jeziellago** [comment]
I'm closing this issue due to no reply.
