### ISSUE TITLE
Invalid compose usage

### ISSUE THREAD

**Issue by jbruchanov** [jeziellago/compose-markdown#9]
Actual version is creating new textview every state change, if I'm not mistaken.
the code should be using something like this
```
val markwon = ...
val text = ...

AndroidView(modifier = modifier,
      factory = { context -> TextView(context)},
      update = { textView -> markwon.setMarkdown(textView, text) }
  )
```

**Comment by jeziellago** [comment]
Hi @jbruchanov 
Could you put any evidence describing the problem?

**Comment by jbruchanov** [comment]
HI @jeziellago 

I think it's misuse of the `AndroidView` API in compose
here
https://github.com/jeziellago/compose-markdown/blob/main/markdowntext/src/main/java/dev/jeziellago/compose/markdowntext/MarkdownText.kt#L57-L76

the factory is a lambda to create a view, 
the implementation ^^ is creating textview each state change and lambda is just passing a reference to new textview and it doesn't behave as a factory....

you would have to wrap it inside a `rememberState` or something like that...

**Comment by jeziellago** [comment]
Hi @jbruchanov 
Thanks for reporting!
I fixed it.
