### ISSUE TITLE
Keep a version of `MarkdownText` in material2

### ISSUE THREAD

**Issue by acouhier-luna** [jeziellago/compose-markdown#94]
Hi,

Thank you for the migration to Material3 in version `0.5.0`. Is it possible to keep a version of `MarkdownText` in Material2?

Details:
* Component: MarkdownText
* Reason: design requirements (We currently are using material2 theme)

Thank you!

**Comment by jeziellago** [comment]
Hi @acouhier-luna 
Could you check if this version works for you? All updates were applied, but without Material 3
```
com.github.jeziellago:compose-markdown:material2-SNAPSHOT
```

**Comment by UniqueTokens** [comment]
The material2 version doesn't work for me. Gradle sync error:

```
Failed to resolve: com.github.jeziellago:compose-markdown:material2-SNAPSHOT
```
