### ISSUE TITLE
Unable to create branch for Pull Request

### ISSUE THREAD

**Issue by mrmichaelmoreau** [jeziellago/compose-markdown#95]
Hi there
I've added support for Font Family and Letter spacing via the style object. 
Would someone please provide me with access to create a branch?

My local branch name is "font-family-and-letter-spacing-support" but I'm unable to push it to remote.

Thanks,

**Comment by jeziellago** [comment]
Hi @mrmichaelmoreau 
Thanks for your collaboration!
You can fork the repository, apply the changes there and open a Pull Request here.

**Comment by mrmichaelmoreau** [comment]
Hi @jeziellago 
My pleasure.
I'm still unable to create a branch

**Comment by jeziellago** [comment]
Hello @mrmichaelmoreau 
I suggest to check this documentation to help you in this process.
https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

**Comment by mrmichaelmoreau** [comment]
Thanks @jeziellago - I've done so now.
